services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    # Expose the Postgres port to the host machine,
    # so you can inspect and administrate it
    ports:
      - "54320:5432"
